### ISSUE TITLE
Bug in data_import.py when opening CSV file.

### ISSUE THREAD

**Issue by NorthonColt** [NorthonColt/Brain-Therapy-Technologies-Project#2]
Error message:

Importing file: C:/Data/ITK MSc/Info Bionics/Semester II/Brain Therapy Technologies/Data 1/Data from first visit/CB27_010305_230417140107.csv
Traceback (most recent call last):
  File "C:\btt-project\src\engine\GUI.py", line 356, in <module>
    data_file, path_to_mydata =data_import.importer(return_path=True)
  File "C:\btt-project\src\engine\data_import.py", line 107, in importer
    list1 = full_list1[unit_loc_inc[1]: unit_location[2]]
IndexError: list index out of range

**Comment by NorthonColt** [comment]
See the XFail test case on the 'data_import_bug_test' branch.

**Comment by batzoriganar** [comment]
The issue was with the csv files and the structure. Now it's resolved. Will modify code to accept different csv structure.

**Comment by hillierdani** [comment]
Tests should be self-contained?
